spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver