spring:
  flyway:
    locations: classpath:db/migration
  jpa:
    show-sql: false
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5441/inventory-control
    username: root
    password: root
    driverClassName: org.postgresql.Driver