CREATE SEQUENCE "PRODUCT_SEQ" START WITH 5 INCREMENT BY 1;

CREATE TABLE PRODUCT (
    ID INT NOT NULL,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    PRICE NUMBER(10, 2),
    PRIMARY KEY(ID)
);

INSERT INTO PRODUCT VALUES(1, 'NOTEBOOK', 'ELETRONICOS', 2200);
INSERT INTO PRODUCT VALUES(2, 'CELULAR', 'ELETRONICOS', 3200);
INSERT INTO PRODUCT VALUES(3, 'CADEIRA', 'CADEIRA', 200);
INSERT INTO PRODUCT VALUES(4, 'CAMA', 'CAMA', 600);