CREATE SEQUENCE SEQ_PRODUCT START WITH 1 INCREMENT BY 1;

CREATE TABLE PRODUCT (
    ID INTEGER NOT NULL,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    PRICE NUMERIC(1000, 2),
    QUANTITY INTEGER NOT NULL,
    PRODUCT_CATEGORY_ID INTEGER,
    PRIMARY KEY(ID)
);

CREATE INDEX IDX_PRODUCT_CATEGORY_ID ON PRODUCT(PRODUCT_CATEGORY_ID);

CREATE SEQUENCE SEQ_CATEGORY START WITH 1 INCREMENT BY 1;

CREATE TABLE CATEGORY (
    ID INTEGER NOT NULL,
    NAME VARCHAR(255),
    PRODUCT_CATEGORY_ID INTEGER,
    PRIMARY KEY(ID)
);

CREATE INDEX IDX_CATEGORY_PRODUCT_ID ON CATEGORY(PRODUCT_CATEGORY_ID);

CREATE TABLE PRODUCT_CATEGORY (
    PRODUCT_ID INTEGER NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID),
    CONSTRAINT FK_CATEGORY_ID FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID)
);